version: "3.9"

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - jupyter-net

  jupyter:
    build: .
    restart: always
    ports:
      - "8008:8888"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DATABASE=${PG_DB}
      - POSTGRES_PORT={PG_PORT}
    volumes:
      - .:/app
    networks:
      - jupyter-net
    depends_on:
      - postgres

volumes:
  postgres-data:
networks:
  jupyter-net:





